import { col, L, BR } from "./colors"
import type { Line } from "./types"

// ── ASCII art logo ─────────────────────────────────────────────────────────────
export const LOGO_LINES: Line[] = [
  BR(),
  L("  ____  __  __  ", col.primary),
  L(" |  _ \\|  \\/  | ", col.primary),
  L(" | |_) | |\\/| | ", col.primary),
  L(" |  _ <| |  | | ", col.primary),
  L(" |_| \\_\\_|  |_| ", col.primary),
  BR(),
  L(" RejectModders Terminal v2.0", col.fg),
  L(" type 'help' to get started", col.muted),
  BR(),
]

export const BOOT_LINES: Line[] = [
  ...LOGO_LINES,
  L("Initializing shell...", col.green),
  L("Loaded 150+ commands. Type 'help' for page 1 of 11, 'help 2' for page 2, etc.", col.muted),
  L("Pro tip: use Tab to autocomplete, ↑/↓ for history.", col.muted),
  BR(),
]

// ── All available command names (for tab completion) ───────────────────────────
export const ALL_CMDS = [
  "help","whoami","ls","ls -la","pwd","cat about","cat readme","cat vulnradar",
  "skills","links","projects","friends","contact","games",
  "status","uptime","date","uname","env","history",
  "echo","ping","curl","hack","matrix","ascii","banner",
  "sudo","rm -rf /","rm -rf / --no-preserve-root","exit","clear",
  "cowsay","fortune","joke","quote","weather","cal","top","ps","df","free",
  "ifconfig","whoishiring","flip","shrug","tableflip","unflip",
  "sl","lolcat","yes","neofetch","cmatrix",
  "man","whois","traceroute","nmap","ssh","git log","git status",
  "vim","nano","emacs","firefox","chrome","reboot","shutdown","dd","touch",
  "coinflip","dice","rps rock","rps paper","rps scissors",
  "base64","rot13","morse","binary","hex",
  "count","timer","stopwatch",
  "color","palette","gradient",
  "crypto","password","uuid",
  "cat secrets.txt","cat .env.local","sudo cat secrets.txt",
  "whoami --verbose","id","groups","last","w","who",
  "netstat","arp","route","dig","nslookup",
  "find","grep","awk","sed","sort","uniq","wc",
  "tar","zip","unzip","gzip","gunzip",
  "chmod","chown","su","useradd","passwd",
  "cron","crontab","at","watch","timeout",
  "kill","killall","pkill","nice","renice",
  "lsof","strace","ltrace","gdb",
  "python","python3","node","ruby","perl","php","java","go","rust","c",
  "npm","pip","cargo","gem","composer",
  "docker","kubectl","terraform","ansible","vagrant",
  "git","git init","git clone","git pull","git push","git commit","git branch","git diff",
  "curl wttr.in","curl parrot.live",
  "2048","snake","tetris","pong","doom",
  "sudo apt install","apt","yum","brew","pacman","dnf",
  "dmesg","journalctl","systemctl","service","init",
  "fsck","mount","umount","fdisk","lsblk","blkid",
  "ip","ip addr","ip route","ss","iptables","ufw",
  "openssl","gpg","ssh-keygen","ssh-copy-id",
  "speedtest","iperf","mtr","tcpdump","wireshark",
  "htop","glances","iotop","nethogs","bmon",
  "tmux","screen","byobu","tty","stty",
  "alias","unalias","export","source","which","whereis","type",
  "ln","readlink","stat","file","md5sum","sha256sum",
  "curl ifconfig.me","curl icanhazip.com",
  "xargs","tee","head","tail","less","more","cat","diff","patch",
  "make","cmake","gcc","g++","clang","rustc","javac",
  "git stash","git tag","git log --oneline",
  "fullscreen","minimize","maximize",
  "rick","doge","nyan","parrot",
  "sudo please","sudo make me a sandwich",
  ":(){ :|:& };:","while true","for i in","exit 1",
  "motd","banner2","figlet","toilet",
  "website","website red","website orange","website yellow","website green",
  "website cyan","website blue","website purple","website pink","website white","website break","website fix","website rainbow",
  "cursor","cursor red","cursor green","cursor blue","cursor cyan","cursor purple",
  "cursor pink","cursor orange","cursor yellow","cursor white","cursor break","cursor fix","cursor rainbow",
  "cursor 1","cursor 2","cursor 3","cursor 4","cursor 5",
  "cat /etc/passwd","cat /etc/os-release","cat /proc/cpuinfo","cat /proc/meminfo",
  "cat /etc/hosts","cat /etc/motd","cat .bashrc","cat /home/rm/todo.txt",
  "ls /","ls /home","ls /home/rm",
  "ps aux","htop","kill","killall","lsof","strace","tee","wc","sort","uniq","diff","find","grep",
  "ip addr","ss","iptables","ufw","curl ifconfig.me","openssl","ssh-keygen","gpg",
  "git stash","git branch","git diff","git log --oneline","git clone",
  "sudo apt install","apt","npm install","brew","docker",
  "which","type","alias","export","source","md5sum","sha256sum","lsblk","mount",
  "python3","python","node","tmux","crontab","watch","id","groups","last","w","who",
  "sudo please","sudo make me a sandwich","sudo please make me a sandwich",
  "help --all", "theme dark", "theme light",
]

// ── Prefix commands for partial matching ───────────────────────────────────────
export const PREFIX_CMDS = [
  "help",
  "man","touch","echo",
  "base64","rot13","morse","binary","hex","md5","md5sum","sha256sum",
  "dice","rps","wget","nslookup","dig",
  "grep","which","file","wc","systemctl","pip","npm",
  "kill","killall","strace","tee","diff","find","export","source","type","watch",
  "openssl","docker","brew",
  "git clone","git stash","git log","git diff","git branch","git",
  "sudo apt install","apt install","apt",
  "npm install","python3","python","node",
  "cursor","theme","website","cowsay","fortune","joke","quote","ping",
  "chmod","chown","useradd","passwd",
]
